### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by Andrea-Torrengo** [Vallauri/inf5aprogetto-Andrea-Torrengo#1]
- # Arduino
- [x] Interfacciamento sensori
- [x] Gestione menu Arduino

- # Android App
- [x] Gestione permessi Bluetooth (BLUETOOTH_ADMIN, BLUETOOTH_FINE_LOCATION...)
- [x] Gestione Bluetooth (Enable/disable, Discovery & pairing)
- [x] Avvio connessione con socket bluetooth
- [ ] Ricezione dal sensore HC06
